### ISSUE TITLE
Add LayerProperty File to EDAFile

### ISSUE THREAD

**Issue by sebastian-goeldi** [gdsfactory/gdatasea#16]
If we store the layerproperty file with the EDAFile, we can a) use it in the renderer (add `?...&layer_props=/folder/path/file.gds`) and b) it allows users to find the proper visualization for their projects/tapeouts easily

**Comment by joamatab** [comment]
sounds good to me

**Comment by Ealameda31** [comment]
Not .gds needs to be a .lyp file. I can add it as validation too.

**Comment by Ealameda31** [comment]
Can I get sample? : )
