### ISSUE TITLE
uploading files

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdatasea#17]
I uploaded a 10MB mask and the file is taking more than 10min ...

- why is this slow?
- can we track progress?
- Can we upload only cells that are going to be tested? For example mark them with labels

@Ealameda31 
@tvt173
@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
Definitely something wrong with your setup. That should be almost instant.

Also, regardong the other issue. I suggest to *not* just skip over the explanation of what wilcards do ;)

**Comment by Ealameda31** [comment]
Which file did you upload @joamatab? Should be super fast.

As @sebastian-goeldi mentioned, there are some docs on the endpoint where you can pass the parent cell names that you are interested in and some wildcards. You could probably help us improve those API docs if they were easy to skim through - I made them purple to highlight :) 

Progress bar for cells and files uploaded? Should be almost instantaneous?
